### PR TITLE
Improve support for allow_none

### PR DESCRIPTION
**Pull request by adamhadani**
This is a re-opening of old PR by @pokey . See https://globality.atlassian.net/browse/GLOB-6119 for context and discussion

There's a pending PR on bravado-core that this PR corresponds to - will update this PR based on results there. mainly re-opening it to re-surface the original commits by pokey so we can test these some more.

### CODE REVIEW

**Comment by pokey** [comment]
@adamhadani There were a couple minor testing improvement commits which should probably be added to this branch: 43b517c5f36dd60a995554418b2cb8d9b3ec463e and pokey/microcosm-flask@37acfbe0f2e896cee369e3bb5710c36a1bfdf75c

**Comment by adamhadani** [comment]
@pokey is your comment about missing commits still relevant here? if so feel free to add them in (tests are currently failing on `microcosm_flask/swagger/schema.py:69:1: C901 'build_parameter' is too complex (16)` but probably easy fix i can look at that a bit later as well)

**Comment by pokey** [comment]
@adamhadani I added the changes to local copy of this branch, but don't have privileges to push to this branch.  Happy to create PR on my own fork, which is what I originally did, or push directly here if you give me access.  Also, fwiw, tests are passing locally for me after rebasing and adding these new tests; we'll see what happens on CI after these changes are pushed here.

**Comment by jessemyers** [comment]
@pokey I added you as a collaborator on this repo.

**Comment by pokey** [comment]
@adamhadani I pushed both those missing commits

**Comment by pokey** [comment]
@adamhadani CI was failing due to the fact that flake8 thought the `build_parameter` function was [too complex](https://flake8.readthedocs.io/en/2.0/#quickstart) (see second half on `--max-complexity`.  [Essentially](https://en.wikipedia.org/wiki/Cyclomatic_complexity) this is because the function has too many `if` statements.  It's checking this because of [this line](https://github.com/globality-corp/microcosm-flask/blob/feature/ah-x-nullable/setup.cfg#L3) in our build config.  I pushed [a commit](https://github.com/globality-corp/microcosm-flask/pull/103/commits/419f3a1451e086ca9eb293e7608fe3da7dfcda2e) that fixes this.  Not sure if that's the right way to go about it, but it does the trick.

**Comment by jessemyers** [comment]
Very old. Closing.

**Pull request closed without merging**
